############################
# HLint Configuration File #
############################

# See https://github.com/ndmitchell/hlint

#######################
# MODULE RESTRICTIONS #
#######################

- modules:
  - {name: Control.Monad.Error, within: []}
  - {name: [Data.Aeson], as: Aeson}
  - {name: Data.ByteString, as: B }
  - {name: Data.ByteString.Char8, as: BC }
  - {name: Data.ByteString.Lazy, as: BL }
  - {name: Data.ByteString.Lazy.Char8, as: BLC }
  - {name: Data.Text, as: T }
  - {name: Data.Text.Lazy, as: TL }
  - {name: Data.Text.Encoding, as: TE }

##########################
# EXTENSION RESTRICTIONS #
##########################

- extensions:
  - default: false # All extension are banned by default
  - name: # Only these listed extensions should be used (to be refined further in the future):
    - ConstraintKinds
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - RankNTypes
    - TemplateHaskell
    - TupleSections

################
# CUSTOM RULES #
################

# Replace a $ b $ c with a . b $ c
- group: {name: dollar, enabled: true}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}
