name:                habulara
version:             0.0.0.4
github:              "telostat/habulara"
license:             BSD3
author:              "Vehbi Sinan Tunalioglu"
maintainer:          "vst@vsthost.com"
copyright:           "Copyright (c) 2020 Telostat Pte Ltd"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Toolkit for Processing Tabular Data
category:            Text, CSV
description:         Please see the README on GitHub at <https://github.com/telostat/habulara#readme>

flags:
  static:
    description: Use static linking for the main executable
    default: false
    manual: true

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cassava
- conduit
- containers
- iconv
- mtl
- scientific
- text
- time
- typed-process
- unordered-containers
- vector
- yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall
  default-extensions:
    - OverloadedStrings

executables:
  habulara:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - habulara
    - optparse-applicative
    when:
      - condition: "flag(static) && !(os(osx))"
        ld-options:
        - -static
        - -pthread

tests:
  habulara-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - habulara
    - QuickCheck
    - quickcheck-instances

  habulara-doctest:
    main:                doctest.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    dependencies:
    - habulara
    - doctest
